kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31017
        hostPort: 31017
  - role: worker
  - role: worker
  - role: worker